# Site settings
title: AnetaCamo | Web development & Illustration
logo: /images/logo.png
description: Hello there
highlighter: rouge
url: '//blog.anetacamova.com'
address: '//blog.anetacamova.com'

encoding: utf-8

# Only use gems that are supported by github
# the gems must be installed on your local system to support jekyll build/serve
# Example
#    $ gem install jekyll-redirect-from
plugins:
  - jekyll-redirect-from
#  - jekyll-responsive-image

# Build settings
markdown: kramdown

collections:
  blogs:
    output: true
    permalink: /blogs/:path/
  tagged:
    output: true
    permalink: /tagged/:path/

defaults:
  -
    scope:
      path: ""
      type: "tagged"
    values:
      layout: "tagged"
  -
    scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog"

# To run in SASS debug mode to the following:
# 1: Make the following directive active (uncomment)
# exclude: [css, _sass]
# 2: From the root of this repo run:
#    sass -I _sass --watch css/main.scss:_site/css/main.css
# 3: Serve like business as usual
#    jekyll serve
# 4: Map you source in DevTools (Chrome browser) as per:
#    https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps
