# Site settings
title: AnetaCamo | Web development & Illustration
description: Hi, my name is Aneta and I am really interested in web designer & illustration.
name: Aneta Camova
logo: /images/logo.png
highlighter: rouge
url: 'anetacamo.github.io'

encoding: utf-8

# Only use gems that are supported by github
# the gems must be installed on your local system to support jekyll build/serve
# Example
#    $ gem install jekyll-redirect-from
plugins:
  - jekyll-redirect-from
#  - jekyll-responsive-image

# Build settings
markdown: kramdown

collections:
  blogs:
    output: true
    permalink: /blogs/:path/
  tagged:
    output: true
    permalink: /tagged/:path/

defaults:
  -
    scope:
      path: ""
      type: "tagged"
    values:
      layout: "tagged"
  -
    scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog"
